### ISSUE TITLE
New surface maps for Pluto system

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/worldwidetelescope.github.io#2]
Put new maps of Pluto system as the stock multi-resolution maps in as the stock multi-resolution (TOAST) data in WWT.  This was an issue in wwt-windows-client (33) and wwt-web-client (81).  I've closed those to put these data issue here in wwt-home.

**Comment by PlanetariumSU** [comment]
I have a Ceres map and model, though it isn't the latest imagery. Vesta would be great to include as well, along with Enceladus, Charon, Titan, etc
