### ISSUE TITLE
Add missing software (e.g. web toastification code) to github

### ISSUE THREAD

**Issue by AstroRob** [WorldWideTelescope/worldwidetelescope.github.io#5]
We are missing some of the core utilities; they should be added so the will be open-sourced and we can track issues, etc.

**Comment by kfogel** [comment]
Hey, @AstroRob.  I invited you to the `wwt-dev` team in GitHub, but you'll need to accept the invitation for it to take effect.

**Comment by kfogel** [comment]
Some tools (from @astrojonathan's workshop presentation today): Sphere Toaster, Study Chopper, AVM import tool, other tools in SDK... See the "TOOLS" slide in Jonathan's presentation (http://wwtworkshops.org/wp-content/uploads/2015/09/WorldWide-Telescope-Eco-System-Overview.pptx, linked to from http://wwtworkshops.org/?tribe_events=wwt-developer-workshop).
